### PR TITLE
doc: add quick start guide

### PR DESCRIPTION
**Pull request by nodiscc**
Explain easiest/most basic usage of Back In Time.

### CODE REVIEW

**Comment by nodiscc** [comment]
ping @Germar

**Comment by buhtz** [comment]
Dear @nodiscc ,
last summer a new team started to maintain Back In Time. I found your PR and won't lose it.
Because the source branch is deleted I'm not able to re-open it. So I created a new PR (#8) based on your PR.

Do you still use Back In Time?

**Comment by nodiscc** [comment]
Hi, thank you for re-creating and merging the PR.
I still use Back In Time.

**Comment by buhtz** [comment]
Great to hear. Maybe you would like to join, doing some code review or just give us your ideas and thoughts.

**Comment by nodiscc** [comment]
I don't think I would be very helpful:
- I use the Debian package (currently at v1.2.1 on Debian 11, planning to upgrade to Debian 12 which has v1.3.3 - I'll report bugs if I find any) - I won't have much time to test newer releases, I enjoy the stability/unchanging nature of the Debian package.
- This is on a single (desktop) machine. On servers I use [rsnapshot](https://rsnapshot.org/). I was thinking of replacing this last backintime instance with rsnapshot for consistency - but I can give it a few more years.
- My usage of backintime is very basic (scheduled weekly run which prompts me to plug in an external USB drive, let BiT backup a few important directories, unmount and unplug USB drive.
- I run higher level backup tasks (fetch data from external sources, run scripts...) from a Makefile (actually `backintime backup` is called from this Makefile). I have contemplated using BiT's user-callback for this, but I like the simplicity of my current method. So I really don't use any advanced features, simply backup a few local directories.
- I have looked through https://github.com/bit-team/backintime/issues, I am not affected by any bugs listed there, nor am I interested in any particular feature request. I like the software as it is, simple, configurable, reliable :+1: 
- What I like about Back In Time compared to other software: good GUI (only relevant to desktops), ability to notify/wait for external target drive before backup, file/hardlink/rsync-based backup method which makes backups very easy to handle/browse/restore, ability to run cleanup tasks after backup (remove old backup generations/preserver some free disk space).

So I will be happy if you keep it this way :) I have started `watch`ing the repository, I will let you know if I something comes up. Good luck with the new project.

**Pull request closed without merging**
